// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v4.25.3
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "../google/protobuf/empty";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "auth";

export interface User {
  id: string;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  confirmed: boolean;
  confirmationToken: string;
  confirmationTokenExpires?: Timestamp | undefined;
  resetPassword?: boolean | undefined;
  resetPasswordToken?: string | undefined;
  resetPasswordTokenExpires?: Timestamp | undefined;
  createdAt?: Timestamp | undefined;
  updatedAt?: Timestamp | undefined;
}

export interface Users {
  users: User[];
}

export interface CreateUserRequest {
  username: string;
  password: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
}

/** GetUserByIDRequest is the request message for retrieving a user by their unique ID. */
export interface GetUserByIDRequest {
  id: string;
}

/** update user request */
export interface UpdateUserRequest {
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  role: string;
  confirmed?: boolean | undefined;
  confirmationTokenExpires?: Timestamp | undefined;
  resetPassword?: boolean | undefined;
  resetPasswordToken?: string | undefined;
  resetPasswordTokenExpires?: Timestamp | undefined;
  updatedAt?: Timestamp | undefined;
  active?: boolean | undefined;
  password?: string | undefined;
  createdAt?: Timestamp | undefined;
  confirmationToken?: string | undefined;
}

/** delete user request */
export interface DeleteUserRequest {
  id: string;
}

export interface UserLoginRequest {
  username: string;
  password: string;
}

/** auth user */
export interface AuthUser {
  id: string;
  username: string;
  role: string;
  confirmed: boolean;
  active: boolean;
  accessToken: string;
  refreshToken: string;
  mustResetPassword?: boolean | undefined;
}

export interface ConfirmEmailRequest {
  token: string;
}

export interface ResetPasswordRequest {
  email: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export const AUTH_PACKAGE_NAME = "auth";

/** UserService provides user-related operations. */

export interface UserServiceClient {
  /** CreateUser creates a new user with the provided information. */

  createUser(request: CreateUserRequest): Observable<User>;

  /** find all users */

  getAllUsers(request: Empty): Observable<Users>;

  /** GetUserByID retrieves a user by their unique ID. */

  getUserById(request: GetUserByIDRequest): Observable<User>;

  /** UpdateUser updates an existing user's information. */

  updateUser(request: UpdateUserRequest): Observable<User>;

  /** DeleteUser deletes a user by their unique ID. */

  deleteUser(request: DeleteUserRequest): Observable<Empty>;

  /** login user */

  login(request: UserLoginRequest): Observable<AuthUser>;

  /** confirm email */

  confirmEmail(request: ConfirmEmailRequest): Observable<Empty>;

  /** reset password */

  resetPassword(request: ResetPasswordRequest): Observable<Empty>;

  /** refresh token */

  refreshToken(request: RefreshTokenRequest): Observable<AuthUser>;
}

/** UserService provides user-related operations. */

export interface UserServiceController {
  /** CreateUser creates a new user with the provided information. */

  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;

  /** find all users */

  getAllUsers(request: Empty): Observable<Users>;

  /** GetUserByID retrieves a user by their unique ID. */

  getUserById(request: GetUserByIDRequest): Promise<User> | Observable<User> | User;

  /** UpdateUser updates an existing user's information. */

  updateUser(request: UpdateUserRequest): Promise<User> | Observable<User> | User;

  /** DeleteUser deletes a user by their unique ID. */

  deleteUser(request: DeleteUserRequest): void | Promise<void>;

  /** login user */

  login(request: UserLoginRequest): Promise<AuthUser> | Observable<AuthUser> | AuthUser;

  /** confirm email */

  confirmEmail(request: ConfirmEmailRequest): void | Promise<void>;

  /** reset password */

  resetPassword(request: ResetPasswordRequest): void | Promise<void>;

  /** refresh token */

  refreshToken(request: RefreshTokenRequest): Promise<AuthUser> | Observable<AuthUser> | AuthUser;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createUser",
      "getAllUsers",
      "getUserById",
      "updateUser",
      "deleteUser",
      "login",
      "confirmEmail",
      "resetPassword",
      "refreshToken",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
